import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/hunter"),
);
const icons = requireAll(require.context("../../assets/icons/hunter"));

export const data: TalentData = {
  "Beast Mastery": {
    name: "Beast Mastery",
    background: backgrounds["beast-mastery"],
    icon: icons["ability_hunter_beasttaming"],
    talents: {
      "Predatory Precision": {
        name: "Predatory Precision",
        pos: "a2",
        icon: icons["inv_misc_head_dragon_black"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the hit chance of your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Ferocity": {
        name: "Ferocity",
        pos: "a3",
        icon: icons["inv_misc_monsterclaw_04"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the critical strike chance of your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Endurance Training": {
        name: "Endurance Training",
        pos: "b3",
        icon: icons["spell_nature_reincarnation"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the Health of your pets by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Bestial Swiftness": {
        name: "Bestial Swiftness",
        pos: "c1",
        icon: icons["ability_druid_dash"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the outdoor movement speed of your pets by ${[
          15,
          30,
          45,
        ]}%`,
      },
      "Soulmate": {
        name: "Soulmate",
        pos: "c2",
        icon: icons["spell_nature_crystalball"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Predatory Precision",
        arrows: [{ dir: "down", from: "a2", to: "c2" }],
        description: talentText`Your next Revive Pet spell has its casting time reduced by 4 sec and its Mana cost reduced by 50%.`,
      },
      "Improved Aspects": {
        name: "Improved Aspects",
        pos: "c3",
        icon: icons["spell_nature_ravenform"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the effect of your Aspects by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Improved Revive Pet": {
        name: "Improved Revive Pet",
        pos: "c4",
        icon: icons["ability_hunter_beastsoothe"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Revive Pet's casting time is reduced by ${[
          2.3,
          4.6,
          7,
        ]} sec, mana cost is reduced by ${[
          30,
          60,
          90,
        ]}%, and increases the health your pet returns with by an additional ${[
          20,
          40,
          60,
        ]}%.`,
      },
      "Spirit Bond": {
        name: "Spirit Bond",
        pos: "d2",
        icon: icons["ability_druid_demoralizingroar"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`While your pet is active, you and your pet will regenerate ${[
          3,
          6,
        ]}% of total health every 10 sec.`,
      },
      "Primal Fury": {
        name: "Primal Fury",
        pos: "d3",
        icon: icons["ability_racial_cannibalize"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Gives your Pet a ${[
          33,
          66,
          100,
        ]}% chance to gain an additional 15 Focus anytime it gets a critical strike.`,
      },
      "Intimidation": {
        name: "Intimidation",
        pos: "e2",
        icon: icons["ability_devour"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Command your pet to intimidate the target on the next successful melee attack, causing a high amount of threat and stunning the target for 3 sec. (45 sec cooldown)`,
      },
      "Bestial Discipline": {
        name: "Bestial Discipline",
        pos: "e3",
        icon: icons["spell_nature_abolishmagic"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increase the Focus regeneration of your pets by ${[
          15,
          30,
          45,
        ]}%.`,
      },
      "Unleashed Fury": {
        name: "Unleashed Fury",
        pos: "f3",
        icon: icons["ability_bullrush"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage done by your pets by ${[
          6,
          12,
          18,
          24,
          30,
        ]}%.`,
      },
      "Bestial Wrath": {
        name: "Bestial Wrath",
        pos: "g2",
        icon: icons["ability_druid_ferociousbite"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Intimidation",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Send your pet into a rage causing 50% additional damage for 18 sec. While enraged, the beast does not feel pity or remorse or fear and it cannot be stopped unless killed. (2 min cooldown)`,
      },
    },
  },
  Marksmanship: {
    name: "Marksmanship",
    background: backgrounds["marksmanship"],
    icon: icons["ability_marksmanship"],
    talents: {
      "Improved Concussive Shot": {
        name: "Improved Concussive Shot",
        pos: "a2",
        icon: icons["spell_frost_stun"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives your Concussive Shot a ${[
          4,
          8,
          12,
          16,
          20,
        ]}% chance to stun the target for 3 sec.`,
      },
      "Efficiency": {
        name: "Efficiency",
        pos: "a3",
        icon: icons["spell_frost_wizardmark"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the Mana cost of your Shots and Stings by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Improved Hunter's Mark": {
        name: "Improved Hunter's Mark",
        pos: "b2",
        icon: icons["ability_hunter_snipershot"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases the Ranged Attack Power bonus of your Hunter's Mark spell by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%`,
      },
      "Lethal Shots": {
        name: "Lethal Shots",
        pos: "b3",
        icon: icons["ability_searingarrow"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Increases your critical strike chance with ranged weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%`,
      },
      "Trueshot Aura": {
        name: "Trueshot Aura",
        pos: "c1",
        icon: icons["ability_trueshot"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increase the attack power of party members within 45 yards by 15. Lasts 30 min.`,
      },
      "Improved Scorpid Sting": {
        name: "Improved Scorpid Sting",
        pos: "c2",
        icon: icons["ability_hunter_criticalshot"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Reduces the Stamina of targets affected by your Scorpid Sting by ${[
          25,
          50,
          75,
        ]}% of the amount of Strength reduced.`,
      },
      "Hawk Eye": {
        name: "Hawk Eye",
        pos: "d2",
        icon: icons["ability_townwatch"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Increases the range of your ranged weapons by ${[
          2,
          4,
          6,
        ]} yards.`,
      },
      "Mortal Shots": {
        name: "Mortal Shots",
        pos: "d3",
        icon: icons["ability_piercedamage"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Lethal Shots",
        arrows: [{ dir: "down", from: "b3", to: "d3" }],
        description: talentText`Increases your ranged weapon critical strike damage bonus by ${[
          6,
          12,
          18,
          24,
          30,
        ]}%.`,
      },
      "Barrage": {
        name: "Barrage",
        pos: "e2",
        icon: icons["ability_upgrademoonglaive"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage done by your Multi-Shot and Volley spells by ${[
          5,
          10,
          15,
        ]}%.`,
      },
      "Scatter Shot": {
        name: "Scatter Shot",
        pos: "e3",
        icon: icons["ability_golemstormbolt"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`A short range shot that deals 50% wepon damage and disorients the target for 4 sec. Any damage caused will remove the effect. Turns off your attack when used. (30 sec. cooldown)`,
      },
      "Ranged Weapon Specialization": {
        name: "Ranged Weapon Specialization",
        pos: "f3",
        icon: icons["inv_weapon_rifle_06"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage your deal with ranged weapons by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Aimed Shot": {
        name: "Aimed Shot",
        pos: "g2",
        icon: icons["inv_spear_07"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Barrage",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`An aimed shot that increases ranged damage by 330 (6 sec. cooldown)`,
      },
    },
  },
  Survival: {
    name: "Survival",
    background: backgrounds["survival"],
    icon: icons["ability_hunter_swiftstrike"],
    talents: {
      "Improved Feign Death": {
        name: "Improved Feign Death",
        pos: "a1",
        icon: icons["ability_rogue_feigndeath"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Reduces the chance your Feign Death ability will be resisted by ${[
          2,
          4,
        ]}%.`,
      },
      "Monster Slaying": {
        name: "Monster Slaying",
        pos: "a2",
        icon: icons["inv_misc_head_dragon_black"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases all damage against Beasts, Giants and Dragonkin targets by ${[
          1,
          2,
          3,
        ]}% and increases critical damage caused against Beasts, Giants and Dragonkin targets by an additional ${[
          1,
          2,
          3,
        ]}%.`,
      },
      "Improved Wing Clip": {
        name: "Improved Wing Clip",
        pos: "a3",
        icon: icons["ability_rogue_trip"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Gives your Wing Clip ability a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to immobilize the target for 5 sec.`,
      },
      "Trap Mastery": {
        name: "Trap Mastery",
        pos: "b1",
        icon: icons["ability_ensnare"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Decreases the chance enemies will resist trap effects by ${[
          5,
          10,
        ]}%.`,
      },
      "Humanoid Slaying": {
        name: "Humanoid Slaying",
        pos: "b2",
        icon: icons["spell_holy_prayerofhealing"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases all damage against Humanoid targets by ${[
          1,
          2,
          3,
        ]}% and increases the critical damage caused against Humanoid targets by an additional ${[
          1,
          2,
          3,
        ]}%.`,
      },
      "Entrapment": {
        name: "Entrapment",
        pos: "b3",
        icon: icons["spell_nature_stranglevines"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives your Immolation Trap, Frost Trap, and Explosive Trap a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to entrap the target, preventing them from moving for 5 sec.`,
      },
      "Clever Traps": {
        name: "Clever Traps",
        pos: "c1",
        icon: icons["spell_nature_timestop"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases the duration of Freezing and Frost trap effects by ${[
          25,
          50,
        ]}% and the damage of Immolation and Explosive trap by ${[25, 50]}%.`,
      },
      "Surefooted": {
        name: "Surefooted",
        pos: "c2",
        icon: icons["ability_kick"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases hit chance by ${[
          1,
          2,
          3,
        ]}% and increases the chance movement impairing effects will be resisted by an additional ${[
          5,
          10,
          15,
        ]}%`,
      },
      "Deterrence": {
        name: "Deterrence",
        pos: "c3",
        icon: icons["ability_whirlwind"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`When activated, increases your Dodge and Parry chance by 25% for 10 sec. (5 min cooldown)`,
      },
      "Survivalist": {
        name: "Survivalist",
        pos: "d2",
        icon: icons["spell_shadow_twilight"],
        maxRank: 5,
        reqPoints: 15,
        description: talentText`Increases total health by ${[2, 4, 6, 8, 10]}%`,
      },
      "Explosive Shot": {
        name: "Explosive Shot",
        pos: "e1",
        icon: icons["spell_fire_flamebolt"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Clever Traps",
        arrows: [{ dir: "down", from: "c1", to: "e1" }],
        description: talentText`Fires an explosive shot, exploding on 5 targets for 270 additional damage.`,
      },
      "Killer Instinct": {
        name: "Killer Instinct",
        pos: "e2",
        icon: icons["spell_holy_blessingofstamina"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your critical strike chance with all attacks by ${[
          2,
          4,
          6,
        ]}%`,
      },
      "Counterattack": {
        name: "Counterattack",
        pos: "e3",
        icon: icons["ability_warrior_challange"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Deterrence",
        arrows: [{ dir: "down", from: "c3", to: "e3" }],
        description: talentText`A strike that becomes active after parrying an opponent's attack. This attack deals 40 damage and immobilizes the target for 5 sec. Counterattack cannot be blocked, dodged, or parried. (5 sec. cooldown)`,
      },
      "Lightening Reflexes": {
        name: "Lightening Reflexes",
        pos: "f3",
        icon: icons["spell_nature_invisibilty"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your Agility by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%`,
      },
      "Wyvern Sting": {
        name: "Wyvern Sting",
        pos: "g2",
        icon: icons["inv_spear_02"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Killer Instinct",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`A stinging shot that puts the target to sleep for 12 sec. Any damage will cancel the effect. When the target wakes up, the Sting causes 0 Nature damage over 12 sec.\n\nOnly one Sting per Hunter can be active on the target at a time. (2 min cooldown)`,
      },
    },
  },
};
