import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/rogue"),
);
const icons = requireAll(require.context("../../assets/icons/rogue"));

export const data: TalentData = {
  Assassination: {
    name: "Assassination",
    background: backgrounds["assassination"],
    icon: icons["ability_rogue_eviscerate"],
    talents: {
      "Improved Backstab": {
        name: "Improved Backstab",
        pos: "a2",
        icon: icons["ability_backstab"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases the critical strike chance of your Backstab ability by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Malice": {
        name: "Malice",
        pos: "a3",
        icon: icons["ability_racial_bloodrage"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Improves your chance to get a critical strike by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Improved Expose Armor": {
        name: "Improved Expose Armor",
        pos: "b1",
        icon: icons["ability_warrior_riposte"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases the armor reduced by your Expose Armor ability by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Dissection": {
        name: "Dissection",
        pos: "b2",
        icon: icons["inv_weapon_shortblade_05"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Improved Backstab",
        arrows: [{ dir: "down", from: "a2", to: "b2" }],
        description: talentText`Reduces the Energy cost of your Backstab ability by ${[
          2,
          4,
          6,
          8,
          10,
        ]}.`,
      },
      "Ruthlessness": {
        name: "Ruthlessness",
        pos: "b3",
        icon: icons["ability_druid_disembowel"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives your finishing moves a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to add a combo point to your target.`,
      },
      "Premeditation": {
        name: "Premeditation",
        pos: "c1",
        icon: icons["spell_shadow_possession"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`When used, adds 1 combo point to your target.  You must add to or use this combo point within 10 sec or the combo point is lost.  1 min cooldown`,
      },
      "Improved Poisons": {
        name: "Improved Poisons",
        pos: "c2",
        icon: icons["ability_poisons"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Improves the chance to apply poisons to your target by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Improved Garrote": {
        name: "Improved Garrote",
        pos: "c3",
        icon: icons["ability_rogue_garrote"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage of your Garrote ability by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Improved Ambush": {
        name: "Improved Ambush",
        pos: "c4",
        icon: icons["ability_rogue_ambush"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Improves the critical strike chance of your Ambush ability by ${[
          25,
          50,
        ]}%.`,
      },
      "Vile Poisons": {
        name: "Vile Poisons",
        pos: "d2",
        icon: icons["ability_rogue_feigndeath"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Improved Poisons",
        arrows: [{ dir: "down", from: "c2", to: "d2" }],
        description: talentText`Increases the damage dealt by your poisons by ${[
          10,
          20,
        ]}% and gives your poisons a ${[
          30,
          60,
        ]}% chance to resist dispel effects.`,
      },
      "Serrated Blades": {
        name: "Serrated Blades",
        pos: "d3",
        icon: icons["inv_sword_17"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`Causes your attacks to ignore 0 of your target's Armor.  The amount of Armor reduced increases with your level.`,
      },
      "Cold Blood": {
        name: "Cold Blood",
        pos: "e2",
        icon: icons["spell_ice_lament"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`When activated, increases the critical strike chance of your next Sinister Strike, Backstab, Ambush, or Eviscerate ability by 100%.  2 min cooldown`,
      },
      "Murder": {
        name: "Murder",
        pos: "e3",
        icon: icons["spell_shadow_deathscream"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage done by your Backstab and Eviscerate abilities by ${[
          2,
          4,
          6,
        ]}%.`,
      },   
      "Opportunity": {
        name: "Opportunity",
        pos: "f3",
        icon: icons["ability_warrior_warcry"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases the damage done when striking from behind with your Backstab, Garrote, or Ambush abilities by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
      "Seal Fate": {
        name: "Seal Fate",
        pos: "g2",
        icon: icons["spell_shadow_chilltouch"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Cold Blood",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Your critical strikes from abilities that add combo points have a 100% chance to add an additional combo point.`,
      },
    },
  },
  Combat: {
    name: "Combat",
    background: backgrounds["combat"],
    icon: icons["ability_backstab"],
    talents: {
      "Remorseless Attacks": {
        name: "Remorseless Attacks",
        pos: "a1",
        icon: icons["ability_fiegndead"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`After killing a target that yields experience or honor, gives you a ${[
          20,
          40,
        ]}% increased critical strike chance on your next Sinister Strike, Backstab, Ambush, or Ghostly Strike.  Lasts 20 sec.`,
      },
      "Precision": {
        name: "Precision",
        pos: "a2",
        icon: icons["ability_marksmanship"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Improves your chance to hit by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Spite": {
        name: "Spite",
        pos: "a3",
        icon: icons["spell_shadow_summonimp"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Improves your chance to get a critical strike by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Improved Gouge": {
        name: "Improved Gouge",
        pos: "a4",
        icon: icons["ability_gouge"],
        maxRank: 3,
        reqPoints: 0,
        description: talentText`Increases the duration of your Gouge ability by ${[
          0.5,
          1,
          1.5,
        ]} sec.`,
      },
      "Improved Sprint": {
        name: "Improved Sprint",
        pos: "b1",
        icon: icons["ability_rogue_sprint"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Gives your Sprint ability a ${[
          50,
          100,
        ]}% chance to remove all movement impairing effects.`,
      },
      "Improved Sinister Strike": {
        name: "Improved Sinister Strike",
        pos: "b2",
        icon: icons["spell_shadow_ritualofsacrifice"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the Energy cost of your Sinister Strike ability by ${[
          2,
          4,
          6,
          8,
          10,
        ]}.`,
      },
      "Rampage": {
        name: "Rampage",
        pos: "b4",
        icon: icons["spell_shadow_unholyfrenzy"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Gives you a ${[
          1,
          2,
          3,
          4,
          5,
        ]}% chance to generate 10 Energy when you deal melee damage.`,
      },
      "Relentless Strikes": {
        name: "Relentless Strikes",
        pos: "c1",
        icon: icons["ability_warrior_decisivestrike"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Your finishing moves have a 20% chance per combo point to restore 25 energy.`,
      },
      "Dual Wield Specialization": {
        name: "Dual Wield Specialization",
        pos: "c2",
        icon: icons["ability_dualwield"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage done by your offhand weapon by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Improved Slice and Dice": {
        name: "Improved Slice and Dice",
        pos: "c4",
        icon: icons["ability_rogue_slicedice"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases the duration of your Slice and Dice ability by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Improved Kick": {
        name: "Improved Kick",
        pos: "d2",
        icon: icons["ability_kick"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives your Kick ability a ${[
          50,
          100,
        ]}% chance to silence the target for 2 sec.`,
      },
      "Lethality": {
        name: "Lethality",
        pos: "d3",
        icon: icons["ability_criticalstrike"],
        maxRank: 3,
        reqPoints: 15,
        prereq: "Spite",
        arrows: [{ dir: "down", from: "a3", to: "d3" }],
        description: talentText`Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, and Hemorrhage abilities by ${[
          10,
          20,
          30,
        ]}%.`,
      },
      "Blade Flurry": {
        name: "Blade Flurry",
        pos: "e2",
        icon: icons["ability_warrior_punishingblow"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your attack speed by 20%.  In addition, attacks strike an additional nearby opponent.  Lasts 15 sec.  2 min cooldown`,
      },
      "Aggression": {
        name: "Aggression",
        pos: "e3",
        icon: icons["ability_racial_avatar"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases the damage done by your Sinister Strike and Eviscerate abilities by ${[
          2,
          4,
          6,
        ]}%.`,
      },
      "Weapon Mastery": {
        name: "Weapon Mastery",
        pos: "f3",
        icon: icons["inv_sword_27"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Gives you a ${[
          1,
          2,
          3,
          4,
          5,
        ]}% chance to get an extra attack on the same target after dealing damage.`,
      },
      "Adrenaline Rush": {
        name: "Adrenaline Rush",
        pos: "g2",
        icon: icons["spell_shadow_shadowworddominate"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Blade Flurry",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Increases your Energy regeneration rate by 100% for 15 sec.  In addition you become immune to stun and incapacitate effects.  2 min cooldown`,
      },
    },
  },
  Subtlety: {
    name: "Subtlety",
    background: backgrounds["subtlety"],
    icon: icons["ability_stealth"],
    talents: {
      "Heightened Senses": {
        name: "Heightened Senses",
        pos: "a2",
        icon: icons["ability_ambush"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Reduces the chance you are hit by spells and ranged attacks by ${[
          1,
          2,
          3,
          4,
          5,
        ]}%.`,
      },
      "Camouflage": {
        name: "Camouflage",
        pos: "a3",
        icon: icons["ability_stealth"],
        maxRank: 5,
        reqPoints: 0,
        description: talentText`Increases your speed while stealthed by ${[
          3,
          6,
          9,
          12,
          15,
        ]}% and reduces the cooldown of your Stealth ability by ${[
          1,
          2,
          3,
          4,
          5,
        ]} sec.`,
      },
      "Pursuit of Injustice": {
        name: "Pursuit of Injustice",
        pos: "b1",
        icon: icons["ability_rogue_feint"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases movement and mounted movement speed by ${[
          5,
          10,
        ]}%.  This does not stack with other movement speed increasing effects.`,
      },
      "Endurance": {
        name: "Endurance",
        pos: "b2",
        icon: icons["spell_shadow_shadowward"],
        maxRank: 5,
        reqPoints: 5,
        description: talentText`Reduces the cooldown of your Sprint and Evasion abilities by ${[
          30,
          60,
          90,
          120,
          150,
        ]} sec.`,
      },
      "Improved Sap": {
        name: "Improved Sap",
        pos: "b3",
        icon: icons["ability_sap"],
        maxRank: 3,
        reqPoints: 5,
        prereq: "Camouflage",
        arrows: [{ dir: "down", from: "a3", to: "b3" }],
        description: talentText`Gives you a ${[
          33,
          66,
          100,
        ]}% chance to return to stealth mode after using your Sap ability.`,
      },
      "Ghostly Strike": {
        name: "Ghostly Strike",
        pos: "c1",
        icon: icons["spell_shadow_curse"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`A strike that deals 125% weapon damage and increases your chance to dodge by 15% for 7 sec.  Awards 1 combo point.  20 sec cooldown`,
      },
      "Elusiveness": {
        name: "Elusiveness",
        pos: "c2",
        icon: icons["spell_magic_lesserinvisibilty"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Reduces the cooldown of your Vanish and Blind abilities by ${[
          30,
          60,
          90,
          120,
          150,
        ]} sec.`,
      },
      "Improved Rupture": {
        name: "Improved Rupture",
        pos: "c3",
        icon: icons["ability_rogue_rupture"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases the damage of your Rupture ability by ${[
          10,
          20,
          30,
          40,
          50,
        ]}%.`,
      },
      "Setup": {
        name: "Setup",
        pos: "c4",
        icon: icons["spell_nature_mirrorimage"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Gives you a ${[
          20,
          40,
          60,
          80,
          100,
        ]}% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "d2",
        icon: icons["spell_shadow_fumble"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Gives you a ${[
          50,
          100,
        ]}% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability.`,
      },
      "Improved Kidney Shot": {
        name: "Improved Kidney Shot",
        pos: "d3",
        icon: icons["ability_rogue_kidneyshot"],
        maxRank: 3,
        reqPoints: 15,
        description: talentText`While affected by your Kidney Shot ability, the target receives an additional ${[
          5,
          10,
          15,
        ]}% damage from all sources.`,
      },
      "Hemorrhage": {
        name: "Hemorrhage",
        pos: "e2",
        icon: icons["spell_shadow_lifedrain"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`An instant strike that damages the opponent and causes the target to hemmorhage, increasing any Physical damage dealt to the target by up to 3.  Lasts 30 charges or 15 sec.  Awards 1 combo point.`,
      },
      "Dirty Deeds": {
        name: "Dirty Deeds",
        pos: "e3",
        icon: icons["spell_shadow_summonsuccubus"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Reduces the Energy cost of your Cheap Shot and Garrote abilities by ${[
          5,
          10,
          15,
        ]}.`,
      },
      "Deadliness": {
        name: "Deadliness",
        pos: "f3",
        icon: icons["inv_weapon_crossbow_11"],
        maxRank: 5,
        reqPoints: 25,
        description: talentText`Increases your Attack Power by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%.`,
      },
      "Veil of Shadows": {
        name: "Veil of Shadows",
        pos: "g2",
        icon: icons["spell_shadow_antishadow"],
        maxRank: 1,
        reqPoints: 30,
        prereq: "Hemorrhage",
        arrows: [{ dir: "down", from: "e2", to: "g2" }],
        description: talentText`Veil yourself in Shadows, removing all disease, poison, magic and bleed effects and absorbing 500 damage for 15 sec.  30 sec cooldown`,
      },
    },
  },
};